# Generated by Django 3.2 on 2021-04-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('contacts', models.CharField(max_length=100, verbose_name='ВК или email')),
                ('who_is_organize', models.CharField(choices=[('Лично', 'Вы лично (активист)'), ('Волонтерское движение', 'Волонтерское движение'), ('НКО', 'НКО'), ('Образовательное учреждение', 'Образовательное учреждение'), ('Молодежная организация', 'Молодежная организация'), ('Администрация города/района', 'Администрация города/района')], default='Лично', max_length=100, verbose_name='Кто будет организатором выставки?')),
                ('date', models.DateField(verbose_name='Когда примерно хотите организовывать выставку?')),
                ('place', models.CharField(max_length=100, verbose_name='Где хотите провести выставку?')),
                ('completed', models.BooleanField(default=False, verbose_name='Проведена ли выставка?')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionApplication',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application_forms.event')),
            ],
            bases=('application_forms.event',),
        ),
        migrations.CreateModel(
            name='QuizzesForStudentsApplication',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application_forms.event')),
                ('quiz_format', models.CharField(choices=[('Малая викторина 45 мин. на класс', 'Малая викторина 45 мин. на класс'), ('Большая викторина 1,5 ч. на 50-100 детей', 'Большая викторина 1,5 ч. на 50-100 детей'), ('Оба варианта', 'Оба варианта')], default='Малая', max_length=50, verbose_name='Какой формат викторин интересует?')),
            ],
            bases=('application_forms.event',),
        ),
    ]
