# Generated by Django 3.2 on 2021-04-23 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitionapplication',
            options={'verbose_name': 'заявку на проведение выставки', 'verbose_name_plural': 'Заявки на проведение выставок'},
        ),
        migrations.AlterModelOptions(
            name='quizzesforstudentsapplication',
            options={'verbose_name': 'заявку на проведение викторины для школьников', 'verbose_name_plural': 'заявки на проведение викторин для школьников'},
        ),
        migrations.AddField(
            model_name='event',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата подачи заявки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='contacts',
            field=models.CharField(max_length=100, verbose_name='Контакты'),
        ),
    ]
