# Generated by Django 3.2 on 2021-04-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0002_auto_20210423_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_date',
            field=models.DateField(auto_now=True, verbose_name='Дата подачи заявки'),
        ),
    ]
