# Generated by Django 3.2 on 2021-05-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0002_auto_20210427_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения мероприятия'),
        ),
    ]
