# Generated by Django 3.2 on 2021-04-23 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0003_alter_event_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_date',
            field=models.DateField(default=datetime.date, verbose_name='Дата подачи заявки'),
        ),
    ]
