# Generated by Django 3.2 on 2021-04-23 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0004_alter_event_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 10, 25, 4, 270345, tzinfo=utc), verbose_name='Дата подачи заявки'),
        ),
    ]
