# Generated by Django 3.2 on 2021-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0005_alter_event_registration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitionapplication',
            options={'verbose_name': 'заявку на проведение выставки', 'verbose_name_plural': 'заявки на проведение выставок'},
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки'),
        ),
    ]
