# Generated by Django 3.2 on 2021-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0006_auto_20210423_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация от заявителя'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes_for_admin',
            field=models.TextField(blank=True, verbose_name='Примечания (как продвигались, где нашли ресурсы на выставку, кто поддержал)'),
        ),
    ]
