# Generated by Django 3.2 on 2021-04-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_forms', '0007_auto_20210424_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='notes_for_admin',
        ),
    ]
