# Generated by Django 3.2 on 2021-04-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Текст')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Выставка', 'Выставка'), ('Викторина', 'Викторина')], max_length=100, verbose_name='Тип')),
                ('status', models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано')], max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'отчет о проведении выставок/викторин',
                'verbose_name_plural': 'отчеты о проведении выставок/викторин',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/reports/', verbose_name='фото')),
                ('report', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии к отчетам',
            },
        ),
    ]
